# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
# There are these two young fish swimming along, and they happen to meet an older fish swimming the other way, who nods at them and says, “Morning, boys. How’s the water?” And the two young fish swim on for a bit, and then eventually one of them looks over at the other and goes, “What the hell is water?”

title: Fabio Filippi
author:
  name: Fabio Filippi
  url: "https://filippi.dev"
  github: "0xFAB10"
  twitter: "0xFAB10"
  threads: "0XFAB10"
  bluesky: "0xfab10.bsky.social"
  linkedin: "0xFAB10"
twitter:
    username: "0xFAB10"
    card: summary
logo: "/assets/logo.png"
email: developers@filippi.dev
description: >- 
  A blog about software development, mainly Shopify.
baseurl: "/"
url: "https://filippi.dev"
remote_theme: jekyll/minima
plugins: [ ]
minima:
  skin: dark
  hide_site_feed_link: true
  social_links:
    - { icon: envelope, category: fa-solid, url: "mailto:fabio@filippi.dev", title: "Send me an email" }
    - { icon: twitter,  url: "https://twitter.com/0xFAB10", title: "I'm not using it anymore" }
    - { icon: threads, url: "https://threads.net/0XFAB10" , title: "Well, it exists"}
    - { icon: linkedin, url: "https://linkedin.com/in/0xFAB10", title: "I have a job, actually" }
    - { icon: bluesky, url: "https://bsky.app/profile/0xfab10.bsky.social", title: "Interesting times" }
    - { icon: chess-knight, category: fa-solid, url: "https://lichess.org/@/jumblejumble",  title: "I wish I was better" }
